from .configuration import CobaldParserConfig
from .modeling_parser import CobaldParser

CobaldParserConfig.register_for_auto_class()
CobaldParser.register_for_auto_class("AutoModelForTokenClassification")